apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistant-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-persistant-storage
        persistentVolumeClaim: 
          claimName: mongo-pv-claim
